//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apple_True_Tone_Recovery.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apple_True_Tone_Recovery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} /  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FORMAT_LABLE {
            get {
                return ResourceManager.GetString("FORMAT_LABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   44 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LIMIT_COVER_BOARD {
            get {
                return ResourceManager.GetString("LIMIT_COVER_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 / 8 Plus benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TEXT_8_8P {
            get {
                return ResourceManager.GetString("TEXT_8_8P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X / Xs / Xs Max benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TEXT_X_XS_XSM {
            get {
                return ResourceManager.GetString("TEXT_X_XS_XSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TEXT_XR {
            get {
                return ResourceManager.GetString("TEXT_XR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Simge) öğesine benzeyen System.Drawing.Icon türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Icon TrueToneRecovery {
            get {
                object obj = ResourceManager.GetObject("TrueToneRecovery", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
